version: '3.9'

services:
  core:
    container_name: core
    build:
      context: /core
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: 8080
      DATABASE_URL: mysql://qywffzyayekkkv1n5ylo:pscale_pw_9EdGQhYgnB19K1XtTfYqWizI4ufZ4I1BJZQxEDhwtva@aws.connect.psdb.cloud/hacknu?sslaccept=strict
    ports:  
      - "8080:8080"

  analysis:
    container_name: analysis
    build:
      context: /analysis
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:  
      - "8000:8000"

